"""
Hard-coded interview round structures for every (role, company) pair.
These ground the GPT extraction and ensure accuracy.
Sources: Glassdoor, Blind, Levels.fyi, company career pages, team-verified JDs.
"""

# ── Data Scientist ────────────────────────────────────────────────────────────

DS_SEEDS = {
    "Google": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume walkthrough"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Statistics"], "question_types": ["1 SQL + 1 Python problem"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Python"], "question_types": ["Live coding on shared doc"]},
            {"name": "Onsite: Stats & ML", "order": 4, "duration_min": 45,
             "skills_tested": ["Probability", "A/B Testing", "Machine Learning"],
             "question_types": ["Statistical inference", "Model evaluation"]},
            {"name": "Onsite: Product Case", "order": 5, "duration_min": 45,
             "skills_tested": ["Product Metrics", "Business Sense"],
             "question_types": ["How would you measure success of X?"]},
            {"name": "Onsite: Googleyness", "order": 6, "duration_min": 45,
             "skills_tested": ["Culture Fit", "Leadership"],
             "question_types": ["Behavioral", "Teamwork"]},
        ],
    },
    "Amazon": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Leadership Principles"],
             "question_types": ["Background + LP-based"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL"], "question_types": ["Complex SQL on CollabEdit"]},
            {"name": "Onsite: SQL Deep Dive", "order": 3, "duration_min": 45,
             "skills_tested": ["Advanced SQL"], "question_types": ["Multi-table", "Window functions"]},
            {"name": "Onsite: Coding & ML", "order": 4, "duration_min": 45,
             "skills_tested": ["Python", "Machine Learning"], "question_types": ["Pandas", "Model building"]},
            {"name": "Onsite: Case Study", "order": 5, "duration_min": 45,
             "skills_tested": ["Business Metrics", "A/B Testing"],
             "question_types": ["Product metrics cases"]},
            {"name": "Onsite: Bar Raiser", "order": 6, "duration_min": 45,
             "skills_tested": ["Leadership Principles"],
             "question_types": ["STAR behavioral questions"]},
        ],
    },
    "Meta": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume review"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 45,
             "skills_tested": ["SQL", "Probability"], "question_types": ["SQL + probability puzzles"]},
            {"name": "Onsite: Quantitative", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Metrics"], "question_types": ["Complex queries", "Metric definition"]},
            {"name": "Onsite: Product Sense", "order": 4, "duration_min": 45,
             "skills_tested": ["Product Analytics", "A/B Testing"],
             "question_types": ["Engagement dropped 5%, diagnose"]},
            {"name": "Onsite: Stats", "order": 5, "duration_min": 45,
             "skills_tested": ["Statistics", "Causal Inference"],
             "question_types": ["Power analysis", "Confidence intervals"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Impact", "Collaboration"],
             "question_types": ["Data-driven decision stories"]},
        ],
    },
    "Apple": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume + motivation"]},
            {"name": "Phone Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Statistics"], "question_types": ["Coding + stats basics"]},
            {"name": "Onsite: Technical", "order": 3, "duration_min": 45,
             "skills_tested": ["Machine Learning", "Statistical Modeling"],
             "question_types": ["Algorithm selection", "Model evaluation"]},
            {"name": "Onsite: Coding", "order": 4, "duration_min": 45,
             "skills_tested": ["Python", "Data Manipulation"],
             "question_types": ["End-to-end data pipeline"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Domain Expertise", "Product"],
             "question_types": ["Team-specific questions"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Innovation"],
             "question_types": ["Handling ambiguity"]},
        ],
    },
    "Netflix": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Impact"],
             "question_types": ["Background", "Data-driven decisions"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Statistics"], "question_types": ["SQL + statistical reasoning"]},
            {"name": "Onsite: SQL & Analysis", "order": 3, "duration_min": 60,
             "skills_tested": ["SQL", "Behavioral Data"],
             "question_types": ["Engagement metrics", "Cohort analysis"]},
            {"name": "Onsite: Experimentation", "order": 4, "duration_min": 60,
             "skills_tested": ["A/B Testing", "Causal Inference"],
             "question_types": ["Design experiments", "Diagnose bias"]},
            {"name": "Onsite: Product", "order": 5, "duration_min": 60,
             "skills_tested": ["Product Metrics", "Business"],
             "question_types": ["Feature evaluation", "Growth metrics"]},
            {"name": "Onsite: Culture", "order": 6, "duration_min": 45,
             "skills_tested": ["Autonomy", "Ownership"],
             "question_types": ["Freedom & responsibility"]},
        ],
    },
    "Microsoft": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background + role fit"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Statistics"], "question_types": ["Coding + stats problem"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "SQL"], "question_types": ["Data manipulation", "Algorithm"]},
            {"name": "Onsite: ML & Stats", "order": 4, "duration_min": 45,
             "skills_tested": ["Machine Learning", "Experimentation"],
             "question_types": ["Model design", "A/B test analysis"]},
            {"name": "Onsite: Product Case", "order": 5, "duration_min": 45,
             "skills_tested": ["Business Metrics", "Product Sense"],
             "question_types": ["Define success for a feature"]},
            {"name": "Onsite: As Appropriate", "order": 6, "duration_min": 45,
             "skills_tested": ["Leadership", "Growth Mindset"],
             "question_types": ["Behavioral", "Values alignment"]},
        ],
    },
    "Tesla": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background + motivation"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["Python", "SQL", "Statistics"], "question_types": ["Coding + stats"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Pandas"], "question_types": ["Data wrangling", "Algorithm"]},
            {"name": "Onsite: ML Deep Dive", "order": 4, "duration_min": 45,
             "skills_tested": ["Machine Learning", "Deep Learning"],
             "question_types": ["Model architecture", "Loss functions"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Automotive Data", "Sensor Data"],
             "question_types": ["Time series analysis", "Anomaly detection"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 30,
             "skills_tested": ["Ownership", "Speed"],
             "question_types": ["Move fast", "First principles"]},
        ],
    },
    "TikTok": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Probability"], "question_types": ["Coding + probability"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Algorithms"], "question_types": ["LeetCode-style medium"]},
            {"name": "Onsite: ML System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Machine Learning", "Recommender Systems"],
             "question_types": ["Design a recommendation pipeline"]},
            {"name": "Onsite: Product & Metrics", "order": 5, "duration_min": 45,
             "skills_tested": ["Product Metrics", "A/B Testing"],
             "question_types": ["Engagement metrics", "Growth analysis"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Culture Fit"],
             "question_types": ["Cross-team work", "Ambiguity"]},
        ],
    },
    "Uber": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + coding problem"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "SQL"], "question_types": ["Data manipulation", "Algorithm"]},
            {"name": "Onsite: Stats & Experimentation", "order": 4, "duration_min": 45,
             "skills_tested": ["Statistics", "A/B Testing", "Causal Inference"],
             "question_types": ["Experiment design", "Surge pricing analysis"]},
            {"name": "Onsite: Case Study", "order": 5, "duration_min": 45,
             "skills_tested": ["Product Metrics", "Business Sense"],
             "question_types": ["Marketplace metrics", "Supply-demand"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Ownership", "Collaboration"],
             "question_types": ["Impact stories"]},
        ],
    },
}

# ── Data Analyst ──────────────────────────────────────────────────────────────

DA_SEEDS = {
    "Google": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume walkthrough"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Spreadsheets"], "question_types": ["SQL query + data interpretation"]},
            {"name": "Onsite: SQL & Analysis", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Data Cleaning"], "question_types": ["Complex joins", "Aggregations"]},
            {"name": "Onsite: Quantitative", "order": 4, "duration_min": 45,
             "skills_tested": ["Statistics", "A/B Testing"],
             "question_types": ["Metric interpretation", "Hypothesis testing"]},
            {"name": "Onsite: Business Case", "order": 5, "duration_min": 45,
             "skills_tested": ["Product Metrics", "Business Sense"],
             "question_types": ["How would you measure success of X?", "Dashboard design"]},
            {"name": "Onsite: Googleyness", "order": 6, "duration_min": 45,
             "skills_tested": ["Culture Fit", "Leadership"],
             "question_types": ["Behavioral", "Teamwork"]},
        ],
    },
    "Amazon": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Leadership Principles"],
             "question_types": ["Background + LP-based"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL on CollabEdit", "Data manipulation"]},
            {"name": "Onsite: SQL & Case Study", "order": 3, "duration_min": 45,
             "skills_tested": ["Advanced SQL", "Business Metrics"],
             "question_types": ["Multi-table joins", "Window functions", "KPI definition"]},
            {"name": "Onsite: Data Visualization", "order": 4, "duration_min": 45,
             "skills_tested": ["Tableau", "Excel", "Storytelling"],
             "question_types": ["Dashboard design", "Chart selection"]},
            {"name": "Onsite: Business Analysis", "order": 5, "duration_min": 45,
             "skills_tested": ["Business Metrics", "A/B Testing"],
             "question_types": ["Root cause analysis", "Product metrics cases"]},
            {"name": "Onsite: Bar Raiser", "order": 6, "duration_min": 45,
             "skills_tested": ["Leadership Principles"],
             "question_types": ["STAR behavioral questions"]},
        ],
    },
    "Meta": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume review"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 45,
             "skills_tested": ["SQL", "Metrics"], "question_types": ["SQL + metric definition"]},
            {"name": "Onsite: SQL & Metrics", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Data Interpretation"],
             "question_types": ["Complex queries", "Metric debugging"]},
            {"name": "Onsite: Product Analytics", "order": 4, "duration_min": 45,
             "skills_tested": ["Product Analytics", "A/B Testing"],
             "question_types": ["Engagement dropped 5%, diagnose", "Feature launch analysis"]},
            {"name": "Onsite: Quantitative", "order": 5, "duration_min": 45,
             "skills_tested": ["Statistics", "Data Interpretation"],
             "question_types": ["Confidence intervals", "Sampling bias"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Impact", "Collaboration"],
             "question_types": ["Data-driven decision stories"]},
        ],
    },
    "Apple": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume + motivation"]},
            {"name": "Phone Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel", "Statistics"], "question_types": ["SQL + spreadsheet basics"]},
            {"name": "Onsite: SQL & Business Analysis", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Business Analysis"],
             "question_types": ["Data extraction", "Report generation"]},
            {"name": "Onsite: Data Visualization", "order": 4, "duration_min": 45,
             "skills_tested": ["Tableau", "Data Storytelling"],
             "question_types": ["Dashboard design", "Insight presentation"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Domain Expertise", "Product"],
             "question_types": ["Team-specific questions"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Innovation"],
             "question_types": ["Handling ambiguity"]},
        ],
    },
    "Netflix": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Impact"],
             "question_types": ["Background", "Data-driven decisions"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL + data interpretation"]},
            {"name": "Onsite: SQL & Data Interpretation", "order": 3, "duration_min": 60,
             "skills_tested": ["SQL", "Behavioral Data"],
             "question_types": ["Engagement metrics", "Cohort analysis"]},
            {"name": "Onsite: Business Case", "order": 4, "duration_min": 60,
             "skills_tested": ["A/B Testing", "Metrics"],
             "question_types": ["Experiment design", "KPI selection"]},
            {"name": "Onsite: Data Storytelling", "order": 5, "duration_min": 60,
             "skills_tested": ["Visualization", "Communication"],
             "question_types": ["Present findings to stakeholders", "Chart selection"]},
            {"name": "Onsite: Culture", "order": 6, "duration_min": 45,
             "skills_tested": ["Autonomy", "Ownership"],
             "question_types": ["Freedom & responsibility"]},
        ],
    },
    "Microsoft": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL + data interpretation"]},
            {"name": "Onsite: SQL & Analysis", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Power BI"], "question_types": ["Complex queries", "Dashboard design"]},
            {"name": "Onsite: Business Case", "order": 4, "duration_min": 45,
             "skills_tested": ["Business Metrics", "Storytelling"],
             "question_types": ["KPI definition", "Stakeholder presentation"]},
            {"name": "Onsite: Stats & Metrics", "order": 5, "duration_min": 45,
             "skills_tested": ["Statistics", "A/B Testing"],
             "question_types": ["Metric interpretation", "Experiment design"]},
            {"name": "Onsite: As Appropriate", "order": 6, "duration_min": 45,
             "skills_tested": ["Growth Mindset", "Collaboration"],
             "question_types": ["Behavioral", "Values alignment"]},
        ],
    },
    "Tesla": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL + spreadsheet manipulation"]},
            {"name": "Onsite: SQL & Reporting", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Data Cleaning"], "question_types": ["Joins", "Aggregations"]},
            {"name": "Onsite: Business Analysis", "order": 4, "duration_min": 45,
             "skills_tested": ["Business Metrics", "Visualization"],
             "question_types": ["Manufacturing KPIs", "Dashboard"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Automotive Data", "Operations"],
             "question_types": ["Supply chain analysis"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 30,
             "skills_tested": ["Ownership", "Speed"],
             "question_types": ["First principles"]},
        ],
    },
    "TikTok": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL + data problems"]},
            {"name": "Onsite: SQL & Metrics", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Product Metrics"],
             "question_types": ["Engagement queries", "Content metrics"]},
            {"name": "Onsite: Product Analytics", "order": 4, "duration_min": 45,
             "skills_tested": ["A/B Testing", "Product Sense"],
             "question_types": ["Feature analysis", "User growth"]},
            {"name": "Onsite: Data Storytelling", "order": 5, "duration_min": 45,
             "skills_tested": ["Visualization", "Communication"],
             "question_types": ["Insight presentation"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Culture Fit"],
             "question_types": ["Cross-team work"]},
        ],
    },
    "Uber": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Excel"], "question_types": ["SQL + data interpretation"]},
            {"name": "Onsite: SQL & Analysis", "order": 3, "duration_min": 45,
             "skills_tested": ["SQL", "Data Cleaning"],
             "question_types": ["Marketplace queries", "Funnel analysis"]},
            {"name": "Onsite: Business Case", "order": 4, "duration_min": 45,
             "skills_tested": ["Business Metrics", "A/B Testing"],
             "question_types": ["Surge pricing analysis", "Conversion optimization"]},
            {"name": "Onsite: Data Storytelling", "order": 5, "duration_min": 45,
             "skills_tested": ["Visualization", "Stakeholder Communication"],
             "question_types": ["Executive summary", "Dashboard design"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Ownership", "Collaboration"],
             "question_types": ["Impact stories"]},
        ],
    },
}

# ── Data Engineer ─────────────────────────────────────────────────────────────

DE_SEEDS = {
    "Google": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + Python coding"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Data Structures"], "question_types": ["LeetCode medium", "Data pipelines"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Distributed Systems", "Data Pipelines"],
             "question_types": ["Design a data pipeline for X", "Batch vs streaming"]},
            {"name": "Onsite: Data Modeling", "order": 5, "duration_min": 45,
             "skills_tested": ["Data Modeling", "SQL", "Schema Design"],
             "question_types": ["Star schema", "Normalization trade-offs"]},
            {"name": "Onsite: Googleyness", "order": 6, "duration_min": 45,
             "skills_tested": ["Culture Fit", "Leadership"],
             "question_types": ["Behavioral", "Teamwork"]},
        ],
    },
    "Amazon": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Leadership Principles"],
             "question_types": ["Background + LP-based"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + system design basics"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Algorithms"], "question_types": ["Data processing", "ETL logic"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["AWS", "Data Pipelines", "Distributed Systems"],
             "question_types": ["Design a real-time pipeline", "Data lake architecture"]},
            {"name": "Onsite: Data Modeling", "order": 5, "duration_min": 45,
             "skills_tested": ["Data Modeling", "Redshift", "SQL"],
             "question_types": ["Warehouse schema", "Partitioning strategies"]},
            {"name": "Onsite: Bar Raiser", "order": 6, "duration_min": 45,
             "skills_tested": ["Leadership Principles"],
             "question_types": ["STAR behavioral questions"]},
        ],
    },
    "Meta": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume review"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + coding problem"]},
            {"name": "Onsite: Coding 1", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Algorithms"], "question_types": ["Data pipeline coding"]},
            {"name": "Onsite: Coding 2", "order": 4, "duration_min": 45,
             "skills_tested": ["Python", "SQL"], "question_types": ["ETL problem", "Data transformation"]},
            {"name": "Onsite: System Design", "order": 5, "duration_min": 45,
             "skills_tested": ["Distributed Systems", "Data Pipelines", "Streaming"],
             "question_types": ["Design data infrastructure for X"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Impact", "Collaboration"],
             "question_types": ["Scale challenges", "Cross-team work"]},
        ],
    },
    "Apple": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Resume + motivation"]},
            {"name": "Phone Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Spark"], "question_types": ["Coding + SQL"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Data Structures"], "question_types": ["Data processing"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Data Pipelines", "Cloud"],
             "question_types": ["Pipeline architecture", "Fault tolerance"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Spark", "Data Modeling"],
             "question_types": ["Team-specific data challenges"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Innovation"],
             "question_types": ["Handling ambiguity"]},
        ],
    },
    "Netflix": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication", "Impact"],
             "question_types": ["Background", "Data-driven decisions"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + Python coding"]},
            {"name": "Onsite: Coding & Pipelines", "order": 3, "duration_min": 60,
             "skills_tested": ["Python", "Spark", "Kafka"],
             "question_types": ["Streaming pipeline", "Data transformation"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 60,
             "skills_tested": ["Distributed Systems", "Data Architecture"],
             "question_types": ["Design Netflix data platform component"]},
            {"name": "Onsite: Data Modeling", "order": 5, "duration_min": 60,
             "skills_tested": ["Data Modeling", "SQL"],
             "question_types": ["Schema design", "Query optimization"]},
            {"name": "Onsite: Culture", "order": 6, "duration_min": 45,
             "skills_tested": ["Autonomy", "Ownership"],
             "question_types": ["Freedom & responsibility"]},
        ],
    },
    "Microsoft": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + coding problem"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Data Structures"], "question_types": ["Data pipeline coding"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Azure", "Data Pipelines", "Distributed Systems"],
             "question_types": ["Design a data ingestion pipeline"]},
            {"name": "Onsite: Data Modeling", "order": 5, "duration_min": 45,
             "skills_tested": ["Data Modeling", "SQL"],
             "question_types": ["Warehouse design", "Partitioning"]},
            {"name": "Onsite: As Appropriate", "order": 6, "duration_min": 45,
             "skills_tested": ["Growth Mindset", "Collaboration"],
             "question_types": ["Behavioral", "Values alignment"]},
        ],
    },
    "Tesla": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background + motivation"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python", "Spark"], "question_types": ["SQL + coding"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Data Structures"], "question_types": ["ETL pipeline coding"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Data Pipelines", "Streaming", "IoT Data"],
             "question_types": ["Design pipeline for 10TB daily ingestion"]},
            {"name": "Onsite: Domain", "order": 5, "duration_min": 45,
             "skills_tested": ["Spark", "Airflow", "Data Modeling"],
             "question_types": ["Manufacturing data pipeline", "Sensor data"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 30,
             "skills_tested": ["Ownership", "Speed"],
             "question_types": ["Move fast", "First principles"]},
        ],
    },
    "TikTok": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + coding problem"]},
            {"name": "Onsite: Coding 1", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Algorithms"], "question_types": ["LeetCode medium-hard"]},
            {"name": "Onsite: Coding 2", "order": 4, "duration_min": 45,
             "skills_tested": ["Python", "Spark"], "question_types": ["Data pipeline problem"]},
            {"name": "Onsite: System Design", "order": 5, "duration_min": 45,
             "skills_tested": ["Distributed Systems", "Streaming", "Kafka"],
             "question_types": ["Design real-time data pipeline"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Collaboration", "Culture Fit"],
             "question_types": ["Cross-team work"]},
        ],
    },
    "Uber": {
        "rounds": [
            {"name": "Recruiter Screen", "order": 1, "duration_min": 30,
             "skills_tested": ["Communication"], "question_types": ["Background"]},
            {"name": "Technical Screen", "order": 2, "duration_min": 60,
             "skills_tested": ["SQL", "Python"], "question_types": ["SQL + coding"]},
            {"name": "Onsite: Coding", "order": 3, "duration_min": 45,
             "skills_tested": ["Python", "Data Structures"], "question_types": ["Data processing algorithm"]},
            {"name": "Onsite: System Design", "order": 4, "duration_min": 45,
             "skills_tested": ["Kafka", "Spark", "Data Pipelines"],
             "question_types": ["Design real-time surge data pipeline"]},
            {"name": "Onsite: Data Modeling", "order": 5, "duration_min": 45,
             "skills_tested": ["Data Modeling", "SQL"],
             "question_types": ["Marketplace data model", "Rider-driver schema"]},
            {"name": "Onsite: Behavioral", "order": 6, "duration_min": 45,
             "skills_tested": ["Ownership", "Collaboration"],
             "question_types": ["Impact stories"]},
        ],
    },
}

# ── Unified lookup ────────────────────────────────────────────────────────────

SEED_DATA = {
    "Data Scientist": DS_SEEDS,
    "Data Analyst": DA_SEEDS,
    "Data Engineer": DE_SEEDS,
}


def get_seed(role: str, company: str) -> dict | None:
    """Return seed data for a (role, company) pair, or None if not available."""
    return SEED_DATA.get(role, {}).get(company)


def get_companies_for_role(role: str) -> list[str]:
    """Return all companies that have seed data for a given role."""
    return list(SEED_DATA.get(role, {}).keys())
